language: php
sudo: required
dist: trusty
group: edge
env:
  - DB=mysql
before_install:
  - travis_retry composer self-update
  - composer install
before_script:
  - mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot;
script: phpunit --configuration phpunit_mysql.xml --coverage-text